// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVlD1e_u1DO2rmyFf-_sTPN7UVCoCy-k',
    appId: '1:657413323565:web:f7d1356d6f975f77e0f1a4',
    messagingSenderId: '657413323565',
    projectId: 'appfaxinei22',
    authDomain: 'appfaxinei22.firebaseapp.com',
    databaseURL: 'https://appfaxinei22-default-rtdb.firebaseio.com',
    storageBucket: 'appfaxinei22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWBdRcpwWwQWWm2PhCT1D4SwL5RKml7dk',
    appId: '1:657413323565:android:991e8e10bc2500bee0f1a4',
    messagingSenderId: '657413323565',
    projectId: 'appfaxinei22',
    databaseURL: 'https://appfaxinei22-default-rtdb.firebaseio.com',
    storageBucket: 'appfaxinei22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDYIZzkuVyKnCf8iI2mq6N9xpKH818KRs',
    appId: '1:657413323565:ios:2c4e4604f79a434be0f1a4',
    messagingSenderId: '657413323565',
    projectId: 'appfaxinei22',
    databaseURL: 'https://appfaxinei22-default-rtdb.firebaseio.com',
    storageBucket: 'appfaxinei22.appspot.com',
    androidClientId: '657413323565-md5h878ni1k1g0mocl14rbiajscr9qad.apps.googleusercontent.com',
    iosClientId: '657413323565-ac0fulr9nqvfb979lad8apc1hptnk039.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
